# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselapp', '0002_requestmeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmeta',
            name='path',
            field=models.CharField(max_length=5000),
        ),
    ]
