# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselapp', '0003_auto_20170108_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.CharField(max_length=2000)),
            ],
        ),
    ]
