# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselapp', '0004_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='metadata',
            field=models.CharField(max_length=5000),
        ),
    ]
