# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 04:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselapp', '0008_auto_20170208_2322'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestMeta',
        ),
    ]
