# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselapp', '0011_estate'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
