# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 06:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counselapp', '0012_estate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='estate',
            field=models.ForeignKey(default='7cb8291c-4847-4ed3-8d6a-0a25ee5d86f8', on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='counselapp.Estate'),
            preserve_default=False,
        ),
    ]
