# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 03:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('counselapp', '0013_visit_estate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounselDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_id', models.CharField(max_length=50, unique=True, verbose_name=b'Device ID')),
                ('reg_id', models.CharField(max_length=255, unique=True, verbose_name=b'Registration ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Name')),
                ('is_active', models.BooleanField(default=False, verbose_name=b'Is active?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
            },
        ),
    ]
