# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 06:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('counselapp', '0014_counseldevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='estates', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
